### ISSUE TITLE
GameEvent's name parameter invalid type hinting

### ISSUE THREAD

**Issue by Tayum** [ChristoMI/Servachok_Dev#1]
https://github.com/ChristoMI/Servachok_Dev/blob/decfd6bff0c90100a0f46e8fcba7f9aa4d163e6c/events.py#L28
parameter should be just `str`, not `EventName` "enum":
`def __init__(self, name: str, kwargs: dict): `

For the example of the same behavior, see `pymongo` source code:
[`class ReturnDocument`] https://github.com/mongodb/mongo-python-driver/blob/f62c53f4727b658ffa40a80ed46cbc0f5c96afa0/pymongo/collection.py#L62

which is then used as:
https://github.com/mongodb/mongo-python-driver/blob/f62c53f4727b658ffa40a80ed46cbc0f5c96afa0/pymongo/collection.py#L2835
___

Change type hinting here, respectively:
https://github.com/ChristoMI/Servachok_Dev/blob/decfd6bff0c90100a0f46e8fcba7f9aa4d163e6c/server.py#L111

to
`def __init__(self, name: str, args: dict): `

**Comment by LobovVitaliy** [comment]
fixed in commit b713d0c61287b86d8aef54495adf22f024d290a1
