### ISSUE TITLE
Explicitly show that GameEvent's clas should not be directly used

### ISSUE THREAD

**Issue by Tayum** [ChristoMI/Servachok_Dev#2]
https://github.com/ChristoMI/Servachok_Dev/blob/decfd6bff0c90100a0f46e8fcba7f9aa4d163e6c/events.py#L27L33
Please mark this class abstract, as well as the `def request()` as abstract method:
```
from abc import ABC, abstractmethod

# ...

class GameEvent(ABC):
    def __init__(self, name: EventName, kwargs: dict):
        self.name = name
        self.payload = kwargs

    @abstractmethod
    def request(self) -> bytes:
        pass
```

In such case we explicitly show that the instances of this class should not be directly used.

**Comment by LobovVitaliy** [comment]
fixed in commit b69d7d3a8ce9ce3ed31bc50340cdfb27f3d881f5
